[package]
name = "amber-aios"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = {version = "0.29", features = ["socket", "net"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
